### ISSUE TITLE
Question about AllowUDPConnections

### ISSUE THREAD

**Issue by SheppeR** [Toemsel/Network#46]
Hi, just wondering about AllowUDPConnections set to false, why tcpconnection close and re open.
It's a bug or intended ?
If not a bug, why close and open again the tcpconnection ?

![21a292ec8992a3b863bb016d1ce522cb](https://user-images.githubusercontent.com/4973320/63623168-2df3ed00-c5f9-11e9-95d7-105761a00274.png)

**Comment by Toemsel** [comment]
Because the server rejects a UDP connection and kills the related TCP connection.

Then the ClientConnectionContainer receives the info that the UDP/TCP is dead and reconnects.

Hence, if you dont allow UDP, you can't use the ClientConnectionContainer. Use the TcpConnection only instead.

Hope that helps

**Comment by SheppeR** [comment]
Thank you for your answer, I will use your suggestion.

**Comment by SheppeR** [comment]
Hum sorry but since create a tcp connection and not a container on client, packets stopped to be send

client is connected but nothing is send from the client

`        private void TestClient()
        {
            var container = ConnectionFactory.CreateTcpConnection("127.0.0.1", 8899, out _);
            container.ConnectionEstablished += Established;
        }

        private void Established(TcpConnection con, UdpConnection arg2)
        {
            Console.WriteLine($@"{con} Connection established");

            con.RegisterPacketHandler<LoginResponse>(OnResponseReceived, this);
            
            con.Send(new LoginRequest("TEST", "TEST"), this);
        }`

**Comment by Toemsel** [comment]
The event subscriber seems strange with TCP and UDP as a parameter. However, please take a look at the examples:

https://www.indie-dev.at/2016/10/03/client-setup/

or on github

https://github.com/Toemsel/Network/blob/master/Examples/NetworkTestClient/SingleConnectionExample.cs

In order to help you even further, please also post the server code. Thanks

**Comment by SheppeR** [comment]
its a auto generated method with parameter from 
![image](https://user-images.githubusercontent.com/4973320/63627945-44567480-c60a-11e9-8ea9-f545365d2b53.png)

The server is exactly the same code as the example from repo but AllowUDPConnections set to false

**Comment by Toemsel** [comment]
Thanks to point that out. It shouldn't be public in first place. Will change that later on.

Regarding your issue, dont use that event... It wont fire, since it will never be called (No UDP possible) and it shouldnt be visible in first place :)

Sorry for the inconvenience

**Comment by SheppeR** [comment]
no problem client send / receive packet now
