### ISSUE TITLE
Close Reason AssemblyDoesNotExist

### ISSUE THREAD

**Issue by ReznicencuBogdan** [Toemsel/Network#52]
Hi! While testing this library I noticed that it fails sending/receiving custom made class packets with the AssemblyDoesNotExist message. The source code for the failing project is [here](https://drive.google.com/drive/folders/1snpksVjw2kkGZonIDpBI1iwF_z8L7QxL?usp=sharing).
The code is nothing else but basically the one provided in the examples section.
The library is used to comunicate between a desktop server(DesktopServer.cs) and xamarin.android client(MainActivity.cs).
Sending raw data works well on the other hand.

**Comment by Toemsel** [comment]
Sending raw data works, because the lib doesn't have to load any libs in order to serialize/deserialize information. Those "packets" are already built in.

That exception occurs, if either the client or sever has no reference to that custom object. If the client sends a custom object to the server, the server needs to know the object's structure. Hence, the client and server need a reference to that class.

Please check out the provided example projects here on github. The best thing would be to create 3 projects:

1. Client App
2. Server App
3. Shared Lib

The shared lib contains all your classes which you want to send over the network. And you simply add the "Shared Lib" as a reference to the Client App and Server App.

Regarding your example: Since there isn't any .csproj I am not able to see whether you did include the classes on the server and client side.
