### ISSUE TITLE
WritePacketThreadException with Unity build on android

### ISSUE THREAD

**Issue by JeffreyR-1746919** [Toemsel/Network#78]
Library works as it should when 2 unity instances are running in the editor, one is the server, the other the client.
But when I build the client to my android phone, the client succesfully connects to the server, but then after a while the server shows the client closed the connection with reason: Timeout. No packet that is sent after the tcp connection is established ever arrives at the server.
Debugging with ADB reveals that the client errors out with a WritePacketThreadException.

**Comment by Toemsel** [comment]
Look at the inner exception. That error indicates an error on your side. Basically the lib cant serialize your object. Either a type isn't supported or you do something during the serialization. Are on both sides the packet assemblies known?

**Comment by JeffreyR-1746919** [comment]
I forgot to mention that it's just the close reason of the client that says WritePacketThreadException. The error happens in the library which i'm unable to get. Also I just commented out all of the sending of packets, and the connection still closes with this reason. The only thing it does is create a TCP connection.

**Comment by Toemsel** [comment]
Can you share the project?

**Comment by JeffreyR-1746919** [comment]
Can't manage to get logging to work on android build, running on phone.
Server log prints some errors: 
[SERVER_LOG.txt](https://github.com/Toemsel/Network/files/6480784/SERVER_LOG.txt)


The code is nothing special, just a client that creates a TCP connection, and server connection container that starts the tcp listener. 

FYI using .NET TcpClient with the same setup (client on android, server on PC) works like a charm.

**Comment by Toemsel** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Server.ConnectionLost
```

Try to set Server.ConnectionLost to a valid instance. However, that wont change anything. I can only guess as there are no relevant logs on the server-side. Only that the client isn't reachable, which you already did describe.

Therefore, my ideas are:
1. The Server part includes classes the client has no access to (Pay attention to share all libraries to both parties)
2. You send an object which has unsupported data-types in it
3. Ensure that the Firewall isn't blocking any traffic (Could be based on your chosen port)

I know that is vague, but so is your report. _WritePacketThreadException_ only occurs if the library cant serialize your packet. As the packet is part of you software, we can't do much here.

Good luck

**Comment by JeffreyR-1746919** [comment]
1. This doesn't make any sense since everything works perfectly when I run the app in the unity editor (including sending custom packets) instead of running a build on my phone.
2. Same as 1. + I'm by the way not even sending any data, the connection just closes.
3. This also doesn't make any sense, since using TcpClient works, as well as sending data using its NetworkStream.
4. Already doing that.
5. See 4.

Well, thanks for the help anyway, I appreciate the quick response.

**Comment by Toemsel** [comment]
Ic. Thanks for the clarification.
```

| TcpConnection | Write object on stream | 192.168.0.142:33844 | System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Linq.Expressions.Interpreter.LightLambda.MakeRunDelegateCtor (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Interpreter.LightLambda.GetRunDelegateCtor (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Linq.Expressions.Expression`1[TDelegate].Compile (System.Boolean preferInterpretation) [0x00000] in <00000000000000000000000000000000>:0 
```

I would have to debug into this issue. It seems to happen here https://github.com/Toemsel/Network/blob/4fcf72487cf2dce7c0f0d78fd52109484018202a/Network/Converter/PacketConverter.cs#L146
However, I have no clue which object is null. Can you share the SDK version of you android project? I would like to reproduce this issue. It might also affect other people as well. Also, are you using Unity for Android?

**Comment by JeffreyR-1746919** [comment]
No problem.

I use Unity version 2020.3.0f1 with Android Build Support.
Minimum API Level is 28, target API level is set to Automatic.
Also I use .NET Standard 2.0

Here is the relevant client code and project settings:
[files.zip](https://github.com/Toemsel/Network/files/6481206/files.zip)

**Comment by Toemsel** [comment]
I could reproduce your scenario. It does work within the editor and also while "live-debugging" directly on the android device. However, after deployment to the phone, it crashes after sending the first packet.

In this regards Unity is pretty strange. Their remote debugging (Unity Remote) is actually a streaming service (same accounts for other platforms like Hololens) which streams the Unity rendered on your PC to the phone. Long story short, while being on your PC, a different .NET Framework will be chosen. While executing the Unity project on android, another version of .NET (I am not sure which specific version of Mono that currently is; OR it also could be cross-compiled to CPP - IL2CPP) takes over, which is sadly not 100% compatible with the .NET Standard 2.0 as it seems.

[Due to this behaviour I am not even able to debug into the issue. Sadly, you can't use this library on android.](https://forum.unity.com/threads/mono-vs-il2cpp.533416/#post-3800950)

`IL2CPP should work fine with any library that works with an AOT platform. If if the library uses dynamic code generation (via System.Reflection.Emit), it won't work with IL2CPP.`

The lib uses Reflection, but doesn't use Reflection.Emit. Not sure if that could be an issue, even though he doesn't mention it.

Addon: You could run the app against Mono, instead of IL2CPP. However, [ARM devices aren't supported](https://answers.unity.com/questions/1351948/why-doesnt-mono-support-arm64.html).

[![Screenshot-2021-05-15-023121.png](https://i.postimg.cc/g2KFtLpB/Screenshot-2021-05-15-023121.png)](https://postimg.cc/gxrTnJnv)
