### ISSUE TITLE
Can this library send and receive structs ? 

### ISSUE THREAD

**Issue by genaray** [Toemsel/Network#80]
I basically search an c# network lib which is capable of sending data oriented structs from the server to the client. Im not making any useage of classes because im using an entity component system architecture.

Is it possible to send/receive structs with this lib in an easy way ?

**Comment by Toemsel** [comment]
Not yet - although technically possible with reflection already - but I will add it as a future feature.

**Comment by Toemsel** [comment]
I dug into this request. In order to support enums, we would require to support field serialization. This feature wouldn't be backward-compatible and might cause issues. I recommend to use "BeforeSend" and "AfterSend" to implement a custom logic for enum conversion. Or, even better, provide a custom packet converter by yourself. (Override the default packet converter)
